name: Publish Coverage Report

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Restore dependencies
      run: |
        cd Bank
        dotnet restore

    - name: Build project
      run: |
        cd Bank
        dotnet build --no-restore

    - name: Run tests with coverage
      run: |
        cd Bank
        dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Generate coverage report
      run: |
        cd Bank
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" -targetdir:"./Cobertura" -reporttypes:Html

    - name: Build Documentation
      run: docfx docfx.json

    - name: Deploy Coverage Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Bank/Cobertura
        destination_dir: coverage

    - name: Deploy Documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        destination_dir: docs